name: eShopOnWeb Build and Test

#Déclencheurs 
on: [push, workflow_dispatch]

#Variables d'environment  https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: AZ204
  LOCATION: francecentral
  TEMPLATE-FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION-ID: 884b7cf4-0fa5-4288-be75-8645ac3a00fe
  WEBAPP-NAME: az204-webapp-gkof


jobs:
  #Build, test & publication du projet.net web dans repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    #Verrouillage du repository
    - uses: actions/checkout@v2
    #prepare l'exécuteur avec le SDK .net 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    #Build/Test/Publication du projet .net 
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
    - name: dotnet publish
      run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
    # Chargement des artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp
        
    # Chargement d'un scénario bicep pour les futures taches de déploiement d'infra
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}
        
  # Utilisation du bicep pour création Webapp et chargment binaires 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    
    #Téléchargment des artifacts précédents
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app
        path: .net-app
  
    #Téléchargment du bicep
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: bicep-template
        path: bicep-template
        
   #Connexion auprès de l'abo Azure (credentials stockés comme GitHub Secret dans le repo)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
           
    # Déploiement de la WebApp avec le fichier Bicep 
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION-ID }}
        resourceGroupName: ${{ env.RESOURCE-GROUP }}
        template: bicep-template/webapp.bicep
        parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
        failOnStdErr: false   
    
    # Publication du site Web vers Azure App Service (WebApp)
    - name: Publish Website to WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP-NAME  }}
        package: .net-app
   
